### ISSUE TITLE
"join our mailing list" link target incorrect

### ISSUE THREAD

**Issue by siebrand** [eloquence/lib.reviews#106]
On https://lib.reviews/?uselang=en, the link "join our mailing list" leads to https://freeculture.org/Mailman/listinfo/lib.reviews. There is no way to join the mailing list from there.

**Comment by eloquence** [comment]
We moved the freeculture.org wiki to a new server; haven't reinstalled mailman yet. Added a maintenance notice for now.

**Comment by eloquence** [comment]
This was fixed a while ago; closing
