### ISSUE TITLE
Add possibility to merge things

### ISSUE THREAD

**Issue by picsi** [eloquence/lib.reviews#108]
Soon enough we'll start seeing duplicated items. Either by user error, or by the same thing having different URLs as themes (like official page, Wikipedia page, OSM location link).

Ideally there should be a way to merge items and perhaps keep the multiple URLs stored.

**Comment by eloquence** [comment]
Yes. I can hand-merge items for now when this occurs, but we'll definitely need a UI for it soon. This is already logged as #7, so closing this report.
