### ISSUE TITLE
Basic Wikidata adapter

### ISSUE THREAD

**Issue by eloquence** [eloquence/lib.reviews#19]
Easy search completion for things to be reviewed powered by Wikidata would be a nice "bootstrapping" feature. Maybe not for first release if it's too complex.

To consider:
- We don't want to review living people
- We want to exclude stuff like disambiguation pages and other Wikimedia-specific stuff
- We may want to "auto-sync" at least descriptions/labels on a regular basis

**Comment by pizzamaker** [comment]
Does this mean entries in lib.reviews will be linked to Wikidata items? I think that would be an excellent solution.

**Comment by eloquence** [comment]
Yes, they would implicitly be linked the moment you pick a Wikidata item to review. The relationship between review subject and identifying URLs is already one-to-many, though we're not currently making that obvious.

**Comment by eloquence** [comment]
We now have a basic Wikidata search/import feature, described in brief here:

https://lib.reviews/team/developers/post/b2245981-0e59-427f-a7fe-8e685b827656

After initial import there's no auto-sync yet, this will be treated as a separate issue.

A more technical breakdown of the feature will be posted to the [Wikidata list](https://lists.wikimedia.org/mailman/listinfo/wikidata) this weekend.

**Comment by picsi** [comment]
This is amazing. I'll add this to https://www.wikidata.org/wiki/Wikidata:Status_updates/Next if you don't mind :)

**Comment by eloquence** [comment]
Thanks! I've added a link to https://lists.wikimedia.org/pipermail/wikidata/2017-July/010961.html which provides a bit more background.
