### ISSUE TITLE
Create first logo

### ISSUE THREAD

**Issue by eloquence** [eloquence/lib.reviews#2]
We'll need at least a placeholder logo for a few places (e.g., getting rid of the Twitter egg).

**Comment by eloquence** [comment]
Reached out to http://ura.al/ to see if they're interested in working on this

**Comment by eloquence** [comment]
Thanks to @elioqoshi we have a first logo & other relevant assets :). Committed to /assets for now

**Comment by elioqoshi** [comment]
Was a pleasure :)
