### ISSUE TITLE
Images appear/disappear depending on selected language.

### ISSUE THREAD

**Issue by aggsol** [eloquence/lib.reviews#211]
Some reviews do not display images in every language. On the current front page some entries display no images when switching between German and English.

**Comment by eloquence** [comment]
The way languages work is that if you change your UI and then make a content change, you create content *in that language*. So there was an English language copy of some of your German reviews, and a German language copy of your English review. I nuked the redundant English language copy of the "Einsamer Wolf" review and the images now show up, for example.

I realize this workflow is fairly confusing, sorry -- content language handling definitely needs work.

**Comment by aggsol** [comment]
Okay, that workflow is *super* confusing. The same happen with the team descriptions.
