### ISSUE TITLE
Picture upload issue

### ISSUE THREAD

**Issue by pnoll1** [eloquence/lib.reviews#213]
I was unable to upload a picture named Screenshot at 2018-09-01 00-46-12.png.  The rich text editor shows the picture as loaded, but the photo doesn't show up in the review when published.  The link and description do show up in the published review.

It is the same file as I uploaded to https://lib.reviews/review/4f18612c-429f-43e8-825f-730d81e73c46.  The file uploaded correctly when I renamed the file to FreeCAD_0.17.png.

**Comment by eloquence** [comment]
Thanks for the report! The file name was not properly escaped before being inserted into the markup. Fixed.
