### ISSUE TITLE
Missing Access-Control-Allow-Origin header for the API

### ISSUE THREAD

**Issue by Rudloff** [eloquence/lib.reviews#226]
Hello,

When calling the API ([this URL](https://lib.reviews/api/thing?url=https://www.openstreetmap.org/node/3783946927), for example), the response does not have any [`Access-Control-Allow-Origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) HTTP header, which means it can not be used in a JavaScript web app.

**Comment by picsi** [comment]
You might have better luck contacting him on IRC/matrix.

**Comment by eloquence** [comment]
Thanks for reporting this; this should be fixed & deployed now (although the API is still super bare bones of course -- the reason it wasn't set yet is that it's so far only consumed by lib.reviews itself for some JS features).

**Comment by Rudloff** [comment]
I confirm it now works correctly, thanks!
