### ISSUE TITLE
Links to TripAdvisor are shown as Yelp-Links in Review sites

### ISSUE THREAD

**Issue by nortix** [eloquence/lib.reviews#250]
When you post a link to a TripAdvisor review it shows up as Yelp on the additional links section, e.g. https://lib.reviews/brocken

**Comment by eloquence** [comment]
Just a smol error in the mapping here: https://github.com/eloquence/lib.reviews/commit/50ae33121f3089a7e1de7f9cbc06b146d2aa2858 - fixed and deployed, sorry for the delay!
