### ISSUE TITLE
update Mastodon contact

### ISSUE THREAD

**Issue by Strubbl** [eloquence/lib.reviews#306]
Since https://mastodon.technology/@lib_reviews is down, do you have any other Mastodon account?

**Comment by eloquence** [comment]
Hi @Strubbl, I pushed and deployed a commit yesterday to update it to https://fosstodon.org/@lib_reviews - you should see it in the English version. Volunteer translators have started updating translations, as well. Please let me know if you don't see it in the English version!

**Comment by Strubbl** [comment]
Looks good in the English version. Thank you.
