### ISSUE TITLE
Add help text for label editing

### ISSUE THREAD

**Issue by eloquence** [eloquence/lib.reviews#51]
The purpose of labels may not be immediately obvious. Let's add context-sensitive help like we have in other places.

**Comment by eloquence** [comment]
Alternatively and/or additionally, if we can make the label step obsolete for most reviews by inserting that field into the form if the API detects we don't already have a given thing, then we could substantially reduce the confusion.

**Comment by tjgillies** [comment]
I was confused by label today. I think I'm still confused. Is the label the name of the "thing"?

**Comment by eloquence** [comment]
Yep, like the title of the movie or book. Definitely needs work to be clearer.

**Comment by eloquence** [comment]
Done.
