### ISSUE TITLE
Implement URLs of specific language versions

### ISSUE THREAD

**Issue by pizzamaker** [eloquence/lib.reviews#73]
It would be handy for sharing it around in non-English speaking communities.

**Comment by pizzamaker** [comment]
Yes I think you're right about that. I know it's a super niche and specific scenario, but my initial thought was about how I'd present this to an Esperanto audience. The website would need to be in that language.

Since I don't know how it's implemented, I'm out of suggestions on how to solve this minor issue.

**Comment by eloquence** [comment]
I think we could also support a one-time language switch parameter, like ?language, which would also tell the user what's happening. (MediaWiki does that with the ?uselang= parameter.) That's a bit trickier to get right and might serve a narrower audience, so I'll focus on the browser detection piece first.

**Comment by pizzamaker** [comment]
Yes! That's exactly what I was imagining. No rush :)

**Comment by eloquence** [comment]
Per-page language selection is now live, with the ?uselang= parameter. We need to translate a few messages for this; I wouldn't recommend using it for a specific language until those translations are done. Example:

https://lib.reviews/new/review?uselang=fr
