### ISSUE TITLE
Merge feeds

### ISSUE THREAD

**Issue by Cj-Malone** [eloquence/lib.reviews#87]
(Thanks for using Atom, not RSS.)
Each language having a separate feed is unnecessary, they can be merged into one feed. Just having multiple titles and contents with xml:lang attributes, or if you do want to keep separate feeds the ids should really be different per feed.

I also would appreciate adding [paged feeds](https://tools.ietf.org/html/rfc5005#section-3).

**Comment by eloquence** [comment]
While I like the idea of merged multilingual feeds, I worry that it would break quite a few feed readers. Unfortunately the different readers implement the standard to different degrees. I've found this to be true even for basic functionality like detecting multiple feeds embedded in a page, where surprisingly many feed readers will just pick the first one they find.

With regard to languages, just trying it with `liferea` for example it seems to pick the last language it encounters for a given element. I haven't tested it more extensively yet; let me know if you have some info on how widely it is supported (or have a nice example feed I can test with). It might make sense to offer it as an option for feed readers that support it.

Good point re: the ID, I think it'll be easiest to just use the feed's URL as the ID then.

Re: paged feeds, it wouldn't be too hard to add that using the same timestamp-offset pagination we use in the web view. I've filed #88 for that.

**Comment by Cj-Malone** [comment]
I've opened an [issue](https://github.com/lwindolf/liferea/issues/442) for liferea, and made an [example feed](https://feeds.betterfeeds.org/examples/multilingual.atom). Their will always be issues with feed readers, ```source``` and even ```author``` have poor support in most.

I personally think that if a reader isn't going to follow the spec then it's on them, but I understand that's not practical so maybe another feed would be the best for compatibility.

**Comment by eloquence** [comment]
Thanks, very helpful. Quick rundown:

- feedreader.com: Picks the first language (e.g., "French Title" shows up as feed title) for any given element
- feedly.com: as above
- quiterss (desktop reader): as above
- Tiny Tiny RSS: as above
- olive and nrss: as above (nrss ignores title and asks user to provide their own)

So far I've not been able to find a reader that gives any indication that it supports multiple languages in a single feed. Is there one your'e using that does?

**Comment by Cj-Malone** [comment]
Sorry this is actually against the Atom spec, I thought as the title and things are language sensitive they could be duplicated but they can't. Separate feeds are required.

I guess you could still do the separate ```id``` per file, and connect the feeds with ```<link rel="archives" type="application/atom+xml" hreflang="en" href="https://lib.reviews/team/6bfc0390-e218-4cb7-a446-2046cb886435/blog/atom/en"/>``` for each language.

I've been improving [AntennaPod](https://github.com/AntennaPod/AntennaPod/) parser, and wanted to do the same with [spaRSS](https://github.com/Etuldan/spaRSS) so I have a half working implemention AntennaPod (and given up on spaRSS, I just can't fix that [parser](https://github.com/Etuldan/spaRSS/blob/master/mobile/src/main/java/net/etuldan/sparss/parser/RssAtomParser.java)) guess I'm deleting that branch.
