### ISSUE TITLE
Rich text editor

### ISSUE THREAD

**Issue by tjgillies** [eloquence/lib.reviews#95]
Something similar to the box I am typing in right now with support for github flavoured markdown

**Comment by tjgillies** [comment]
Just realized we already have github flavoured markdown theres just no buttons. closing.

**Comment by keunes** [comment]
I guess it would be nice to have buttons for that - if you want to reach less technical audiences (or just make it convenient for people who don't want to remember different markup defaults). I'd suggest to re-open unless there's another issue covering this ;)

**Comment by eloquence** [comment]
Yeah, I think a toolbar or even an optional markdown-compatible RTE might be nice. Here are a few to consider:

- https://simplemde.com/
- https://github.com/fuksito/markdown-toolbar
- https://stackedit.io/
- https://github.com/OscarGodson/EpicEditor (demo:  https://epiceditor-demos.herokuapp.com/ )

I personally like EpicEditor, which gets out of the way if you're writing something quick/simple, but offers distraction-free full-screen editing with preview if/when you need it. Any thoughts on different options, especially based on prior experience writing lots of stuff in markdown?

**Comment by eloquence** [comment]
Here's a more comprehensive evaluation of the "WYSIWYG" options:
https://docs.google.com/spreadsheets/d/1wrLiZQk3xokl02RjLWEIpTH6cBZYirEnj1yCgCV9SHA/edit#gid=0

I am leaning towards ProseMirror. This would allow us to have a WYSIWYM editor for people who don't like markdown, and a (possibly enhanced) markdown mode for everyone else. It's designed to be hackable and seems very active, though there may be a bit more leg work involved in getting it integrated than with some other options. On the flip side, it seems to be very future-proof.

I'm not fond of the options which combine markdown with formatting -- those seem to be "the worst of both worlds", no real preview and no real simplicity.

**Comment by eloquence** [comment]
RTE branch will land soon, see https://github.com/eloquence/lib.reviews/commit/0de5dada8536f78c7b535dc5a4d7a58f78037545 for a summary of current state.

**Comment by eloquence** [comment]
This is now live; blog post to follow shortly. Some known issues + more will come up, I'm sure -- bug reports welcome! 

See rte-component label:
https://github.com/eloquence/lib.reviews/issues?q=is%3Aissue+is%3Aopen+label%3Acomponent-rte
